### ISSUE TITLE
Keep manifest files in folders

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/open-energy-modeling-benchmarks#15]
for better reproducibility

**Comment by odow** [comment]
I haven't done this because it is a bit of a pain if I am on Mac, you are on Windows, and CI is on Linux?

**Comment by odow** [comment]
We could just use pinned compat bounds

**Comment by joaquimg** [comment]
Compat bounds are not enough, one of the big issues with Sienna was a dependency that is not fixed.
If systems are a problem, can we unify to Linux?
I can run Linux from windows easily, would that work on mac?

**Comment by odow** [comment]
> one of the big issues with Sienna was a dependency that is not fixed

Add that as an explicit dependency

**Comment by joaquimg** [comment]
That is doable but then we never know when there will be another one of these.
A plan b would be to keep the manifest with a modified name or inside some folder.

**Comment by joaquimg** [comment]
I created the manifest files on windows and all tests are running smoothly on linux.
We can re-open if an issues appears
