### ISSUE TITLE
Report the primal integral

### ISSUE THREAD

**Issue by odow** [jump-dev/open-energy-modeling-benchmarks#17]
We could use HiGHS' callback feature to report the primal integral. This might be more useful for the MIPLIB etc. And if we add heuristics, this will also show up as an improvement.

We could even add the primal integral as an `info` field to upstream?

**Comment by odow** [comment]
@jajhall is this already implemented in HiGHS? If not, is it something we can add?

**Comment by jajhall** [comment]
I don't think that we compute the primal integral, but it's not hard to add.

**Comment by joaquimg** [comment]
This would be useful for comparing MIPs and selecting benchmarks in a more automated way.
