### ISSUE TITLE
CuOpt for large-scale SCOPF and SCED

### ISSUE THREAD

**Issue by mzy2240** [jump-dev/open-energy-modeling-benchmarks#19]
Saw this [article](https://developer.nvidia.com/blog/accelerate-large-linear-programming-problems-with-nvidia-cuopt/) yesterday about solving large LP problem using Nvidia's CuOpt. Would be interesting to see if Nvidia's optimized PDLP implementation outperforms the traditional method on large-scape SCOPF (single-snapshot) and SCED (multi-snapshot, fixed commitments from Day Ahead clearings), especially with tons of transmission security constraints.

**Comment by odow** [comment]
Closing because this topic (while interesting) is out-of-scope for this project.
